dist: bionic
sudo: required
language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo chmod +x install_gtest.sh
- "./install_gtest.sh"
script:
- chmod +x build.sh
- ./build.sh
- doxygen doxygen_config.conf
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
  - provider: pages
    local_dir: doxygen/html
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    repo: pokachopotun/otus-cpp.github.io
    on:
      branch: master
