language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- chmod +x build.sh
- ./build.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
  - chmod +x deploy.sh
  - ./deploy.sh
