sudo: required
language: cpp
before_script:
- sudo add-apt-repository ppa:jonathonf/gcc
- sudo apt-get install gcc-9
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo chmod +x install_gtest.sh
- "./install_gtest.sh"
script:
- chmod +x build.sh
- ./build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
